### ISSUE TITLE
[Exchange Rate API] Normalize or apply algorithm to reduce amount of data returned for exchange rate chart to FE

### ISSUE THREAD

**Issue by dragons3232** [klubcoin/mv-liquichain-exchange-rates#1]
Currently BE API returns 9250 points for 1d exchange data, and it caused FE to stall to render chart

Expected result: BE API should reduce amount of points while maintaining chart shape. Regardless of date range, it should return same amount of data enough to render on small mobile device's screen. Recommended 1000 points maximum

Suggested algorithm: https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm

**Comment by tonysviews** [comment]
O(n) iterative implementation of the algorithm: https://gist.github.com/stohrendorf/aea5464b1a242adca8822f2fe8da6612

**Comment by tonysviews** [comment]
Moved the ticket details to [mv-liquichain-payment](https://github.com/liquichain/mv-liquichain-payment/issues/1)
